nelmio_cors:
    defaults:
        allow_origin: ["http://localhost:3000"]
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
        origin_regex: true
        allow_credentials: true
    paths:
        "^/api/":
            allow_origin: ["http://localhost:3000"]
